Smaller fontsize for YaruExpanders
ubuntu-flutter-community/software pull request #1089
Opened 2023-02-17 22:26 UTC by madsrh

@anasereijo mentioned making the expander titles a bit smaller. It quickly became a mess, so @Jupi007 suggested creating a YaruExpandableTitle widget. 

Current master:
![image](https://user-images.githubusercontent.com/3986894/219804254-da6d76f9-ab0f-49fb-af08-795fb94f95fe.png)

PR:
![image](https://user-images.githubusercontent.com/3986894/219804139-dd593bad-2faf-4bd2-a8f1-a957c0e165e9.png)

<img width="540px" src="https://user-images.githubusercontent.com/3986894/219805231-9f9a41a9-ebc9-4a38-8e76-fb557af7d6fa.gif">

2023-02-17 23:21 UTC, Jupi007 requested changes

2023-02-17 23:21 UTC, Jupi007 commented on lib/app/common/expandable_title.dart
> +  }) : super(key: titleKey);
@madsrh here you just need to do:

```dart
const YaruExpandableTitle(
  this.title, {
  super.key
});
```

No need to create an intermediate `titleKey` property 🙂

2023-02-18 10:08 UTC, Jupi007 commented on lib/app/common/expandable_title.dart
> +  const YaruExpandableTitle(this.title, {super.key});
Just had a thought, this will only be used on expandable containers, so what about renaming this widget into `ExpandableContainerTitle`? Because we have some other expandable who won't use this widget, and so I think a specific name would be better.

If you agree, you just need to press F2 after clicking on this (in VS code) to be able to rename all occurrences quickly 🙂

2023-02-18 10:44 UTC, madsrh commented on lib/app/common/expandable_title.dart
> +  const YaruExpandableTitle(this.title, {super.key});
As you can see, pressing F2 clearly didn't work for me 😆 Sorry for all the commits in the PR.

2023-02-18 11:35 UTC, Jupi007 approved these changes
LGFM 👍

But let's wait @Feichtmeier opinion before merging 🙂

2023-02-18 14:19 UTC, Feichtmeier approved these changes

2023-02-18 14:19 UTC, merged