AlertDialog for removing snap
ubuntu-flutter-community/software pull request #1098
Opened 2023-02-20 10:17 UTC by madsrh

Fixes https://github.com/ubuntu-flutter-community/software/issues/988

I was unsure about the wording (not provided in the issue), so I've simply used already existing string.

![image](https://user-images.githubusercontent.com/3986894/220076791-ed59eefe-04eb-4a56-a517-9687d48b2ee5.png)

2023-02-20 10:22 UTC, madsrh commented
Yes! I've set a record in most failed tests 💪 🏆 

Sorry, I have no idea why. It works fine here and I've checked with `flutter analyze`

2023-02-20 10:25 UTC, d-loose commented
> Sorry, I have no idea why. It works fine here and I've checked with `flutter analyze`

It's my fault - sorry for the disturbance! See #1097

2023-02-20 10:59 UTC, d-loose requested changes

2023-02-20 10:59 UTC, d-loose commented on lib/app/collection/simple_snap_controls.dart
> +                                  child: const Text('Cancel'),
Can we use the localization string here?

2023-02-20 10:59 UTC, d-loose commented on lib/app/collection/simple_snap_controls.dart
> +                                  child: const Text('Remove'),
Another localization string, please :)

2023-02-20 10:59 UTC, d-loose commented on lib/app/collection/simple_snap_controls.dart
> +                                '${context.l10n.remove} ${model.snap.apps.first.name}?',
I think it would be better to have a dedicated localization string for package removal with the app name as a parameter, because there're probably languages where "\<word for remove\> *app name*?" isn't correct.

2023-02-20 11:57 UTC, d-loose commented on lib/app/collection/simple_snap_controls.dart
> +                                '${context.l10n.remove} ${model.snap.apps.first.name}?',
I've opened a PR on your PR :)

2023-02-20 12:08 UTC, d-loose approved these changes
LGTM :+1:

2023-02-20 18:12 UTC, Feichtmeier approved these changes

2023-02-22 12:05 UTC, anasereijo commented
title: Remove "foobar2000"
text: Are you sure you want to remove this package?
buttons: they look nice, but I think Remove could be red (we do that in other products)

2023-02-22 12:08 UTC, madsrh commented
Yes! 

Now, with the help from Dennis, I can fix that. I'll adjust the PR

2023-02-22 22:49 UTC, closed without merging