Add animation to back gesture
ubuntu-flutter-community/software pull request #587
Opened 2022-12-01 19:22 UTC by whiskeyPeak

This adds an animation to the back gesture, both when the page is popped and not.

https://user-images.githubusercontent.com/73116038/205141351-587f1a65-0d90-4bb9-8c2a-3fa435ca9ca9.mp4

2022-12-01 19:25 UTC, whiskeyPeak commented
I'd make an issue but I feel like this change is simple enough that it doesn't require any :sweat_smile:

2022-12-01 19:31 UTC, Jupi007 requested changes
Thanks a lot @whiskeyPeak, animated stuff are always nice 😀

2022-12-01 19:31 UTC, Jupi007 commented on lib/store_app/common/app_page/app_swipe_gesture.dart
> +      });
Use a timer for this is really not ideal and you should use an animation controller instead with the `SingleTickerProviderStateMixin` mixin.
It would be manually piloted in `onPanStart/Update` function, and the controller should be reversed in `onPanEnd`.

2022-12-01 19:34 UTC, whiskeyPeak commented on lib/store_app/common/app_page/app_swipe_gesture.dart
> +      });
Ok, will give this a look!

2022-12-01 22:14 UTC, whiskeyPeak commented
@Jupi007 Using an animation controller now. PTAL!

2022-12-01 22:24 UTC, Jupi007 requested changes
Thanks @whiskeyPeak 🙂
I added another comment.

2022-12-01 22:24 UTC, Jupi007 commented on lib/store_app/common/app_page/app_swipe_gesture.dart
> +    });
Add `setState` in a listener is a bad practice, you should prefer use an `AnimatedBuilder`.

2022-12-01 22:26 UTC, whiskeyPeak commented on lib/store_app/common/app_page/app_swipe_gesture.dart
> +    });
I initially implemented it like that but the build method looked somewhat convoluted with all the different return statements. Will change back though

2022-12-01 22:53 UTC, whiskeyPeak commented
It works but looks pretty weird imo

2022-12-01 23:36 UTC, Jupi007 commented
That you can do, is keep the same logic as in the previous iteration with the controler listener which change `xPosition`, but without `setState`. 🙂

2022-12-01 23:53 UTC, Jupi007 commented on lib/store_app/common/app_page/app_swipe_gesture.dart
> +  late AnimationController swipeController;
As this controller only controls the back animation, I think it would be named `swipeBackController`.

2022-12-02 00:01 UTC, Jupi007 commented on lib/store_app/common/app_page/app_swipe_gesture.dart
> +    );
Use an `AnimationController` value as it seems weird to me, I think you should store `xPosition` as an `Animation<double>` 🤔

2022-12-02 00:14 UTC, whiskeyPeak commented on lib/store_app/common/app_page/app_swipe_gesture.dart
> +  late AnimationController swipeController;
done

2022-12-02 00:17 UTC, whiskeyPeak commented on lib/store_app/common/app_page/app_swipe_gesture.dart
> +    );
I don't understand. Are you saying I should use a Tween to animate the button from kMaxExtent to 0 - kButtonSize instead of using xPosition -= (xPosition + _kButtonSize) * swipeBackController.value?

2022-12-02 10:43 UTC, Jupi007 commented on lib/store_app/common/app_page/app_swipe_gesture.dart
> +    );
After really thought about it, I think just use the `AnimationController` is fine 🙂
The goal is just to animate the back gesture.

2022-12-02 14:11 UTC, whiskeyPeak commented on lib/store_app/common/app_page/app_swipe_gesture.dart
> +    );
Ok, done!

2022-12-02 15:00 UTC, Jupi007 requested changes
Just a little nitpick, and then LGFM 🙂

2022-12-02 15:00 UTC, Jupi007 commented on lib/store_app/common/app_page/app_swipe_gesture.dart
> +    });
Just a little nitpick 😉, you can use this shorter syntax:
```
swipeBackController = AnimationController()..addListener();
```

2022-12-02 15:25 UTC, Jupi007 approved these changes
LGFM 👍

2022-12-03 09:56 UTC, Feichtmeier approved these changes

2022-12-03 10:15 UTC, merged