Update dialog text fixes
ubuntu-flutter-community/software pull request #850
Opened 2023-01-22 16:23 UTC by madsrh

Okay, this does works and fixes some issues, but I'm sure there's a better way of doing this :sweat_smile: 

Fixes #849 849
- text color and size in "package description"
- adds a URL tooltip
- even padding for the window content

I would have likes to also add padding between each expander and hide the entire line with Website when no url is provided :man_shrugging:

2023-01-22 19:20 UTC, Feichtmeier commented
run

```
dart fix --apply
```

to fix all the trailing comma issues without doing anything :)

2023-01-22 19:22 UTC, Jupi007 requested changes
@madsrh I just take a look, and I noticed that the text color problem is related to `YaruTile` and so should be fixed in yaru_widgets.

So can you revert your changes related to this, and open an issue there? :)

I also added a few comments.
Feel free to ask help if my explanations are too obscure.

2023-01-22 19:22 UTC, Jupi007 commented on lib/app/updates/update_dialog.dart
> +          child: Padding(
The padding looks weird with the `BorderContainer` container, because it has already a padding, so the text is shifted to the right currently.

![image](https://user-images.githubusercontent.com/36476595/213935745-29db00f3-684c-4ff8-86b4-89fd1544022b.png)

The `Padding` widget should be removed imo.

2023-01-22 19:22 UTC, Jupi007 commented on lib/app/updates/update_dialog.dart
> +        child: BorderContainer(
With a container, the expandable title is too close from the border imo:

![Capture d’écran du 2023-01-22 20-18-17](https://user-images.githubusercontent.com/36476595/213935595-cfedc7e1-beda-4e2c-b5bd-535fb0efa72e.png)

So can you wrap each `BorderContainer`, with something like a bottom `Padding` of 16:

![Capture d’écran du 2023-01-22 20-18-28](https://user-images.githubusercontent.com/36476595/213935593-be870bc0-c701-4ca5-ae4d-e007145afff7.png)
```dart
Padding(
  padding: const EdgeInsets.only(bottom: 16),
  child: BorderContainer(
    // ...
  ),
)

2023-01-22 19:24 UTC, Jupi007 commented
> run
> 
> ```
> dart fix --apply
> ```
> 
> to fix all the trailing comma issues without doing anything :)

In addition of formatting :)

```
dart fix --apply
dart format --apply
```

2023-01-22 19:25 UTC, Feichtmeier commented
didnt know the last one :O does this fix the import?

2023-01-22 19:27 UTC, Feichtmeier commented
((( Note: we should some day put a `final theme = Theme.of(context);` at the start of build at re-use it here. Quite many calls (by me! :D)

2023-01-22 19:30 UTC, Jupi007 commented
Sorry, looks like this command is just reporting errors in the code 😅

2023-01-22 22:43 UTC, madsrh commented
Adding this did not work for me:

```
Padding(
  padding: const EdgeInsets.only(bottom: 16),
```

Can we fix this later? 😅

2023-01-22 23:39 UTC, Feichtmeier commented
No, you are trapped here for eternity 😅

I'll check tomorrow what's happening in here

2023-01-27 10:28 UTC, Feichtmeier approved these changes

2023-01-27 10:33 UTC, Feichtmeier commented on lib/app/updates/update_dialog.dart
> +        child: BorderContainer(
@madsrh do you plan to implement @Jupi007 change request? 😄

2023-01-27 11:21 UTC, madsrh commented on lib/app/updates/update_dialog.dart
> +        child: BorderContainer(
Adding the padding didn't work, but no, I've found another issue so if it's okay, I would like to close this PR and make a new (simpler) one.

2023-01-27 11:28 UTC, Feichtmeier commented on lib/app/updates/update_dialog.dart
> +        child: BorderContainer(
😃 sure

2023-01-27 12:14 UTC, closed without merging